webstore-master/WebStore/Controllers/CheckoutController.cs
using System.Text;
using Microsoft.AspNetCore.Mvc;
using WebStore.DAL;
using WebStore.Models;

namespace WebStore.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly WebStoreContext _context;
        public CheckoutController(WebStoreContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            string? cookieCart = string.Empty;
            var hasValue = HttpContext.Request.Cookies.TryGetValue("cart", out cookieCart);
            string? cookieUser = string.Empty;
            var hasUser = HttpContext.Request.Cookies.TryGetValue("username", out cookieUser);

            if (!hasValue || !hasUser)
            {
                return View();
            }
            List<Product> products = new List<Product>();
            string cookie = cookieCart.Normalize();
            string user = cookieUser.Normalize();
            cookie = Encoding.UTF8.GetString(Convert.FromBase64String(cookie));
            var order = new Models.Order { PlacedBy = user, State = OrderState.Placed };
            _context.Orders.Add(order);
            _context.SaveChanges();
            foreach (var productId in cookie.Split(","))
            {
                var OrderItem = new OrderItem { OrderId = order.Id, ProductId = int.Parse(productId) };
                var p = _context.Products.First(p => p.Id == int.Parse(productId));
                p.StockCount -= 1;
                _context.OrderItems.Add(OrderItem);
            }
            Response.Cookies.Delete("cart");
            _context.SaveChanges();
            return View(order);
        }

        public IActionResult Cart()
        {
            string? cookieCart = "";
            var hasValue = HttpContext.Request.Cookies.TryGetValue("Cart", out cookieCart);
            List<Product> products = new List<Product>();   
            if (!hasValue)
            {
                return View(products);
            }
            else
            {
                string cookie = cookieCart.Normalize();
                cookie = Encoding.UTF8.GetString(Convert.FromBase64String(cookie));
                foreach (var productId in cookie.Split(","))
                {
                    var p = _context.Products.First(p => p.Id == int.Parse(productId));
                    products.Add(p);
                }
                return View(products);
            }
        }
    }
}

webstore-master/WebStore/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebStore.DAL;
using WebStore.Models;
using WebStore.Filters;
namespace WebStore.Controllers
{
    public class OrdersController : Controller
    {
        private readonly WebStoreContext _context;

        public OrdersController(WebStoreContext context)
        {
            _context = context;
        }

        // GET: Orders
        [CustomAuth("CEO")]
        public async Task<IActionResult> Index()
        {
              return _context.Orders != null ? 
                          View(await _context.Orders.ToListAsync()) :
                          Problem("Entity set 'WebStoreContext.Orders'  is null.");
        }
     

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.Include("OrderItems").Include("OrderItems.Product")
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PlacedBy,State")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            var viewOrder = new OrderViewModel() { PlacedBy = order.PlacedBy, State = order.State };
            if (order == null)
            {
                return NotFound();
            }
            return View(viewOrder);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PlacedBy,State")] OrderViewModel orderView)
        {
            if (id != orderView.Id)
            {
                return NotFound();
            }

 
            if (ModelState.IsValid)
            {
                var order = await _context.Orders
                    .FirstAsync(m => m.Id == id);
                order.State = orderView.State;
                order.PlacedBy = orderView.PlacedBy;
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            return View(orderView);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'WebStoreContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
          return (_context.Orders?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

webstore-master/WebStore/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebStore.DAL;
using WebStore.Filters;
using WebStore.Models;

namespace WebStore.Controllers
{
    public class ProductsController : Controller
    {
        private readonly WebStoreContext _context;

        public ProductsController(WebStoreContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            var webStoreContext = _context.Products.Include(p => p.Category);
            return View(await webStoreContext.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .Include(m => m.Reviews)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        [CustomAuth("CEO")]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Description");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,StockCount,ReleaseDate,CategoryId")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Description", product.CategoryId);
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Description", product.CategoryId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,StockCount,ReleaseDate,CategoryId")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Description", product.CategoryId);
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Products == null)
            {
                return Problem("Entity set 'WebStoreContext.Products'  is null.");
            }
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                _context.Products.Remove(product);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
          return (_context.Products?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

webstore-master/WebStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - WebStore</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/WebStore.styles.css" asp-append-version="true" />
</head>
@inject IHttpContextAccessor context
@{

	string? cookieUser = string.Empty;
	var hasUser = context.HttpContext.Request.Cookies.TryGetValue("username", out cookieUser);
}
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
	                    <li class="nav-item">
		                    <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
	                    </li>
	                    @if (!hasUser)
                        {
	                        <li class="nav-item">
		                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SignUp">Sign Up</a>
	                        </li>
	                        <li class="nav-item">
		                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SignIn">Sign In</a>
	                        </li>
                        }
	                    else
	                    {
		                    <li class="nav-item">
			                    <a class="nav-link text-dark" asp-area="" asp-controller="Checkout" asp-action="Cart">Cart</a>
		                    </li>
		                    <li class="nav-item">
			                    <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
		                    </li>
		                    <li class="nav-item">
			                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SignOut">Sign Out (@cookieUser)</a>
		                    </li>
	                    }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>